spring.application.name=animalShelter
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/my_spring_project
spring.datasource.username=my_user
spring.datasource.password=my_password

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true